#!/usr/bin/env python3


def findPath(maze, start, movable_pos):
    direction = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    temp_movable_pos = list(movable_pos)
    temp_movable_pos.remove(start)

    path = []

    level_search = {}
    trace_back = {}

    level = 1
    level_search[level] = set()
    level_search[level].add(goal)

    continue_flag = 1
    while continue_flag == 1:
        for pos in level_search[level]:
            if maze[pos[0]][pos[1]] == 'o':
                continue_flag = 1
                end = (pos[0], pos[1])
                break
            else:
                level += 1
                level_search[level] = set()
                if pos in temp_movable_pos:
                    temp_movable_pos.remove(pos)
                for d in direction:
                    temp_pos = (pos[0] + d[0], pos[1] + d[1])
                    if temp_pos in temp_movable_pos:
                        level_search[level].add(temp_pos)
                        trace_back[i].add(temp_pos)
    
    search_key = end

    while search_key != start:
        for key, values in trace_back.items():
            for value in values:
                if value == search_key:
                    search_key = key
                    path.append(search_key)
                    break

    r_path = []

    for i in range(len(path)):
        r_path.append(path.pop())

    return(r_path, len(r_path))
